#!/bin/bash


WEB=$(wget --tries=10 --timeout=20 --spider http://google.com  2>&1 | grep OK)

if [ ! "$WEB" != "" ]; then
	/etc/init.d/network-manager stop
	sleep 2
	echo 0 > /sys/bus/usb/devices/1-1/authorized 
	sleep 5
	echo 1 > /sys/bus/usb/devices/1-1/authorized 
	sleep 5
	/etc/init.d/network-manager start
else
	echo "good" >&2
fi

